PDK: ihp-sg13g2
layers:
  Activ:
    algorithm: Square
    density: 45
    deviation: 5
    tile_width: 400
  GatPoly:
    algorithm: Overlap
    density: 25
    deviation: 3
    tile_width: 400
  Metal1:
    algorithm: Square
    density: 50
    deviation: 10
  Metal2:
    algorithm: [Track, Square]
    density: 50
    deviation: 10
    tile_width: 400
  Metal3:
    algorithm: [Track, Square]
    density: 50
    deviation: 10
    tile_width: 400
  Metal4:
    algorithm: [Track, Square]
    density: 50
    deviation: 10
    tile_width: 400
  Metal5:
    algorithm: [Track, Square]
    density: 50
    deviation: 10
    tile_width: 400
  TopMetal1:
    algorithm: Square
    density: 40
    deviation: 10
  TopMetal2:
    algorithm: Square
    density: 40
    deviation: 10
