PDK: ihp-sg13cmos5l
layers:
  Activ:
    algorithm: Square
    density: 50
    deviation: 1
    tile_width: 400
  GatPoly:
    algorithm: Overlap
    density: 25
    deviation: 1
    tile_width: 400
  Metal1:
    algorithm: Square
    density: 50
    deviation: 1
  Metal2:
    algorithm: [Track, Square]
    density: 50
    deviation: 1
    tile_width: 400
  Metal3:
    algorithm: [Track, Square]
    density: 50
    deviation: 1
    tile_width: 400
  Metal4:
    algorithm: [Track, Square]
    density: 50
    deviation: 1
    tile_width: 400
  TopMetal1:
    algorithm: Square
    density: 60
    deviation: 1
